# --- 第一部分：部署控制器 (Deployment) ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-deployment
spec:
  replicas: 1                     
  selector:
    matchLabels:
      app: my-portfolio
  template:                       # 這是 Pod 的模板
    metadata:
      labels:
        app: my-portfolio
    spec:
      containers:
      - name: my-portfolio-container
        image: louisvong1/louis-portfolio:v2.1
        imagePullPolicy: Always   # <--- 加入這一行！(注意縮排要對齊 image)
        ports:
        - containerPort: 80

---
# --- 第二部分：服務入口 (Service) ---
apiVersion: v1
kind: Service
metadata:
  name: portfolio-service
spec:
  type: ClusterIP              
  selector:
    app: my-portfolio             # 這行意思是：把流量導向標籤是 "my-portfolio" 的 Pod
  ports:
    - protocol: TCP
      port: 80                    # 外部訪問的 Port
      targetPort: 80              # 容器內部的 Port